### ISSUE TITLE
Sorting patients by family name then given name does not seem to work.

### ISSUE THREAD

**Issue by travistcummings** [jamesagnew/hapi-fhir#198] opened 2015-07-17 21:03 UTC
Hi, I am using this query:

/Patient/_search?name=&_count=25&_sort%3Aasc=family&_sort%3Aasc=given

To attempt to get all patients sorted by family name, then given name.  I get a bundle back in an order I can't determine, but definitely isn't the right order.  For example:

Aaron Alexis
Daniel Adams
Frank Taylor
Lisa Coleman
Anthony Coleman
Patrick Taylor

And am expecting:
Daniel Adams
Aaron Alexis
Anthony Coleman
Lisa Coleman
Frank Taylor
Patrick Taylor

Thanks!

**Comment by jamesagnew** [comment] 2015-07-18 19:30
Thanks for reporting! Committing a fix shortly!

This was a pretty big bug in the way sorting worked, the sort was searching by all indexes of the same type as the parameter you used as opposed to just the specific one you selected. This has been fixed.

**Comment by travistcummings** [comment] 2015-07-20 18:13
Hi James,

Thanks for the quick response!  Is this fix in 1.2-SNAPSHOT?  I tried to install and use that version but get an error saying:

Could not find the HAPI-FHIR structure JAR on the classpath for version DSTU2_HL7ORG. Note that as of HAPI-FHIR v0.8, a separate FHIR strcture JAR must be added to your classpath (or project pom.xml if you a
/DSTU2

Another question for you, we have a client that is needing very much to have java.io.Serializable functionality in the FHIR resource implementation.  I created a forum post for this:

https://groups.google.com/forum/#!topic/hapi-fhir/KXZ4n5zyIxc

Is this something you would be able to support quickly?  Alternatively, we would branch from your 1.1 release and add this functionality ourselves to get our client unblocked.


Thank you,

Travis Cummings
travis@iSalusConsulting.com

**Comment by jamesagnew** [comment] 2015-07-20 19:24
Hi Travis,

A recent change in the JPA server accidentally introduced a dependency on the RI structures project. Temporarily, if you want to use the 1.2-SNAPSHOT version of the server (where this fix got deployed) you need to also add that dependency on your project:
```xml
<dependency>
   <groupId>ca.uhn.hapi.fhir</groupId>
   <artifactId>hapi-fhir-structures-hl7org-dstu2</artifactId>
   <version>1.2-SNAPSHOT</version>
</dependency>
```

Hoping to remove that dependency shortly, so this won't be a problem for long. Will reply to the Google Group post separately.

**Comment by travistcummings** [comment] 2015-07-20 22:28
I believe I am using the fix and it doesn't seem to work on the secondary sort of given name.  I am using 1.2-SNAPSHOT and seeing these results now.  As you can see, Lisa Coleman and Sarah Graham are out of order.

Daniel Adams
Aaron Alexis
Carol Allen
Ruth Black
Brian Brooks
Susan Clark
Amy Clark
Anthony Coleman
Steven Coleman
Lisa Coleman
Ruth Cook
Betty Davis
Joshua Diaz
Brian Gracia
Stephan Graham
Sarah Graham

**Comment by jamesagnew** [comment] 2015-07-21 01:14
Hi Travis,

Unfortunately I'm not able to reproduce this, even in a test using your exact data. A few questions:
* Is this using Derby or another DB?
* Do searches with only a sort for family and only a sort for given both return the expected results?

**Comment by jamesagnew** [comment] 2015-08-24 02:33
Closing old bugs. Please feel free to reopen if this is still happening.

**Comment by vlad-ignatov** [comment] 2017-06-02 16:20
It seems like this is still broken. I am trying it on (STU3) https://sb-fhir-stu3.smarthealthit.org/smartstu3/open/Patient and I am not able to get sorted results no mather what query I use (`_sort=name`, `_sort=given` or `_sort=family`).

**Comment by jamesagnew** [comment] 2017-06-02 17:25
Hmm. @travistcummings Any idea what version of HAPI that server is based on?

This definitely works for me on our reference server at least: http://fhirtest.uhn.ca/baseDstu3/Patient?_sort=name

**Comment by vlad-ignatov** [comment] 2017-06-02 17:36
According to the conformance statement it should be `2.4` while the reference server is `2.5-SNAPSHOT`.

**Comment by jamesagnew** [comment] 2017-06-09 17:00
So, HAPI 2.5 has been released, and it has fairly significant rewrites to the search code, including sorting. Probably the next thing to do is to test once the SMART server has been upgraded.

I'm not seeing this issue locally, so I'm going to assume whatever caused this has been fixed. Please feel free to comment or re-open if this continues.

**Closed by jamesagnew** 2017-06-09 17:00 UTC

**Comment by travistcummings** [comment] 2017-06-28 03:53
Hi James,

Can you tell me if v2.5 is compatible with a schema and data from a 2.4 install? 

Thanks for your excellent FHIR server!

Travis
