### ISSUE TITLE
Support for resource compartment on server side.

### ISSUE THREAD

**Issue by crinacimpian** [jamesagnew/hapi-fhir#140] opened 2015-03-31 06:33 UTC
Does HAPI-FHIR supports compartment - http://www.hl7.org/implement/standards/fhir/extras.html#compartment, on the server side. For example, for /Patient/123/Observation, the server returns patient demographics instead of patient 123's observations.
I see support on the client side: http://jamesagnew.github.io/hapi-fhir/doc_rest_client.html#Search_-_Compartments. 
Thanks.

**Comment by jamesagnew** [comment] 2015-04-02 16:54
Hi @crinacimpian  - We sure do! You will find information on how to implement compartments on the server here: http://jamesagnew.github.io/hapi-fhir/doc_rest_operations.html#Compartments

**Comment by jamesagnew** [comment] 2015-04-02 16:55
Closing - Please feel free to re-open if you feel the issue isn't done with. :)

**Closed by jamesagnew** 2015-04-02 16:55 UTC
Labels: question
