### ISSUE TITLE
Error while compiling project 

### ISSUE THREAD

**Issue by vpl-profess** [jamesagnew/hapi-fhir#1545] opened 2019-10-16 11:33 UTC
**Describe the bug**
I've tried to recompile the full project from the master.zip on linux ubuntu VM.
The `mvn install` command fails with the following output

```
[INFO] hapi-fhir-spring-boot-sample-client-okhttp ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-server-jersey ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-server-jpa ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.447 s
[INFO] Finished at: 2019-10-16T13:26:49+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata (downstream) on project hapi-fhir-base: Execution downstream of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata failed.: NullPointerException -> [Help 1]

```

**Comment by jamesagnew** [comment] 2019-10-16 13:16
Duplicate of #1356 - Please comment on that bug

**Closed by jamesagnew** 2019-10-16 13:16 UTC
