### ISSUE TITLE
Contained resource disappears when placed in a bundle

### ISSUE THREAD

**Issue by magnuschatt** [jamesagnew/hapi-fhir#368] opened 2016-05-19 12:13 UTC
**What works:**
I create a MedicationOrder and add a Medication as a contained resource.
I encode the MedicationOrder to JSON, and parse it back to a MedicationOrder and the contained Medication resource is still there.

**What doesn't work:**
I create a MedicationOrder and add a Medication as a contained resource.
I place the MedicationOrder in a bundle and encode->parse the bundle.
Now when I retrieve MedicationOrder the Medication is gone.

**Comment by magnuschatt** [comment] 2016-05-19 13:51
Okay this issue seems to be very closely related to https://github.com/jamesagnew/hapi-fhir/issues/350 .
I'm working with a profiled version of MedicationOrder, where the allowed types of the myMedication field has been constrained to ResourceReferenceDt, instead of being a choice between CodeableConceptDt and ResourceReferenceDt. In other words, the field type has been changed from IDatatype to ResourceReferenceDt. If I change it back to IDatatype the Medication survives the bundle encode->parse.

**Comment by magnuschatt** [comment] 2016-05-20 07:59
These warnings appear:
[main] WARN ca.uhn.fhir.parser.ParserState - Resource contains unknown local ref: #1
[main] WARN ca.uhn.fhir.parser.LenientErrorHandler - Unknown element 'medication' found while parsing

**Comment by jamesagnew** [comment] 2016-05-22 19:12
Hi Magnus, I've committed a unit test which tries to replicate this, but it passes for me.

Can you provide a code sample and/or PR against the unit test that demonstrates the issue?

**Comment by jamesagnew** [comment] 2016-06-08 21:37
I'm going to close this, as I'm not able to replicate. Please feel free to re-open if the issue is still occurring for you on the latest 1.6-SNAPSHOT build (or newer)

**Closed by jamesagnew** 2016-06-08 21:37 UTC
