### ISSUE TITLE
Since hapi-fhir-validation r5 structure jar seems to be required when profile snapshot generation is done for a r4 context

### ISSUE THREAD

**Issue by Thopap** [jamesagnew/hapi-fhir#2058] opened 2020-08-29 18:59 UTC
When updating from hapi-fhir 5.0.2 to 5.1.0 hapi-fhir-validation profile snapshot generation is no longer possible, when the r5 resources are not on the classpath. But when only r4 is needed, the assumption is, that r5 resource jar is not required.

Our code try to generate a Snapshot for a r4 resource (r4 resource jar is on the classpath): `new SnapshotGeneratingValidationSupport(fhirContext).generateSnapshot(`

Then the following exception occure when update to 5.1.0:
`Caused by: java.lang.IllegalStateException: Could not find the HAPI-FHIR structure JAR on the classpath for version R5. Note that as of HAPI-FHIR v0.8, a separate FHIR strcture JAR must be added to your classpath (or project pom.xml if you are using Maven)
	at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:172) ~[hapi-fhir-base-5.1.0.jar:?]
	at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:164) ~[hapi-fhir-base-5.1.0.jar:?]
	at ca.uhn.fhir.context.FhirContext.forR5(FhirContext.java:1037) ~[hapi-fhir-base-5.1.0.jar:?]
	at org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper.<clinit>(VersionSpecificWorkerContextWrapper.java:57) ~[hapi-fhir-validation-5.1.0.jar:?]
	at org.hl7.fhir.common.hapi.validation.support.SnapshotGeneratingValidationSupport.generateSnapshot(SnapshotGeneratingValidationSupport.java:102) ~[hapi-fhir-validatjar:?]`

The change #1862, implemented with 5.1.0 seems to introduce the issue.

**Expected behavior**
generateSnapshot can be triggered for a r4 context, without having r5 resource jar on the classpath. If the r5 resource jar is really mandatory, the pom shall declare it as required (currently optional=true).

**sidenote:**
The exception contain a short type "...FHIR strcture JAR  ...." - character "u" is missing.

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.1.0

**Comment by jamesagnew** [comment] 2020-08-29 21:35
This is by design. In order to provide the most up-to-date snapshot generator across all FHIR versions, we use a single R5 codebase and convert structures between R5 whatever version is being snapshotted.. This is great for maintainability buit does mean that you are required to have R5 structures on your classpath. Unfortunately I don't see any way around this, so this is a WONTFIX

**Closed by jamesagnew** 2020-08-29 21:35 UTC

**Comment by Thopap** [comment] 2020-08-30 09:47
@jamesagnew : Thank you for clearify this. If the r5 structure jar is required now, does it make sense to remove the "<optional>true</optional>" in the pom for this dependency?

**Comment by jamesagnew** [comment] 2020-08-30 14:16
@Thopap That's a good idea. Doing so now.
