### ISSUE TITLE
after upgrading the fhir 0.9, the xmlParser cannot convert the contained resources correctly

### ISSUE THREAD

**Issue by baopingle** [jamesagnew/hapi-fhir#144] opened 2015-04-01 05:15 UTC
Fhir 0.9, add a Observation into DiagnosticReport contained resources, then the parser.encodeResourceToString(report), the result xml does not include the contained resources. This can be worked fine with 0.8 release version

**Comment by jamesagnew** [comment] 2015-04-02 03:00
I added a unit test for this and I am not able to reproduce so far. Are you able to provide a code snippet that demonstrates the issue?

**Comment by baopingle** [comment] 2015-04-02 04:41
@ResourceDef(name="Observation",id="reportobservation")
public class ReportObservation extends Observation {

	/**
     * Each extension is defined in a field. Any valid HAPI Data Type
     * can be used for the field type. Note that the [name=""] attribute
     * in the @Child annotation needs to match the name for the bean accessor
     * and mutator methods.
     */
    @Child(name="mandatory", order=0)  
	@Extension(url="#mandatory", definedLocally=true, isModifier=false)
	@Description(shortDefinition="The report observation is mandatory or not")
	private BooleanDt mandatory;
	
    @Child(name="readOnly",order=1)
	@Extension(url="#readOnly", definedLocally=true, isModifier=false)
	@Description(shortDefinition="The report observation is read only or not")
	private BooleanDt readOnly;
    
    @Child(name="defaultCursor",order=2)
   	@Extension(url="#defaultCursor", definedLocally=true, isModifier=false)
   	@Description(shortDefinition="The report observation is default cursor or not")
    private BooleanDt defaultCursor;
    
    @Child(name="sectionContentId",order=3)
   	@Extension(url="#sectionContentId", definedLocally=true, isModifier=false)
   	@Description(shortDefinition="The primary key of the report section content")
    private StringDt sectionContentId;
	
	/**
     * It is important to override the isEmpty() method, adding a check for any
     * newly added fields.
     */
    @Override
    public boolean isEmpty() {
        return super.isEmpty() && ElementUtil.isEmpty(mandatory, readOnly,defaultCursor,sectionContentId);
    }
    
    /********
     * Accessors and mutators follow
     *
     * IMPORTANT:
     * Each extension is required to have an getter/accessor and a stter/mutator.
     * You are highly recommended to create getters which create instances if they
     * do not already exist, since this is how the rest of the HAPI FHIR API works.
     ********/
    
    /** Getter for mandatory */
    public BooleanDt getMandatory(){
    	if(mandatory==null){
    		mandatory = new BooleanDt(false);
    	}
    	return mandatory;
    }
    
    /** Setter for mandatory */
    public ReportObservation setMandatory(Boolean isMandatory){
    	mandatory = new BooleanDt(isMandatory);
    	return this;
    }
    
    /** Getter for readOnly */
    public BooleanDt getReadOnly(){
    	if(readOnly==null){
    		readOnly = new BooleanDt(false);
    	}
    	return readOnly;
    }
    
    /** Setter for readOnly */
    public ReportObservation setReadOnly(Boolean isReadOnly){
    	readOnly = new BooleanDt(isReadOnly);
    	return this;
    }
    
    /** Getter for defaultCursor */
    public BooleanDt getDefaultCursor(){
    	if(defaultCursor==null){
    		defaultCursor = new BooleanDt(false);
    	}
    	return defaultCursor;
    }
    
    /** Setter for defaultCursor */
    public ReportObservation setDefaultCursor(Boolean isDefaultCursor){
    	defaultCursor = new BooleanDt(isDefaultCursor);
    	return this;
    }

    /** Getter for sectionContentId */
	public StringDt getSectionContentId() {
		if(sectionContentId == null){
			sectionContentId = new StringDt();
		}
		return sectionContentId;
	}

	 /** Setter for sectionContentId */
	public ReportObservation setSectionContentId(String sectionContentId) {
		this.sectionContentId = new StringDt(sectionContentId);
		return this;
	}
    
    
}

public class ReportTest{
         @Test
	public void testReportSerialize(){
		DiagnosticReport report = new DiagnosticReport();
		
		ReportObservation obsv = new ReportObservation();
		obsv.getName().addCoding().setCode("name");
		obsv.setValue(new StringDt("value test"));
		obsv.setStatus(ObservationStatusEnum.FINAL);
		obsv.setReliability(ObservationReliabilityEnum.OK);
		obsv.getIdentifier().setSystem("System");
		obsv.getIdentifier().setValue("id value");
		report.getContained().getContainedResources().add(obsv);
                
                IParser parser = new FhirContext().newXmlParser().setPrettyPrint(true);
		String message = parser.encodeResourceToString(report);
		System.out.println(message);
		Assert.assertTrue(StringUtils.contains(message, "contained"));
		Assert.assertTrue(StringUtils.isNotEmpty(message));
	}
}

**Comment by jamesagnew** [comment] 2015-04-02 12:04
In the example above, the parser is omitting the contained resource because there are no references to it from anywhere else in the resource. If you either add the contained resource directly to the parent it will be included:
```
report.addResult().setResource(obsv);
```
Or alternately you can create a link by ID:
```
obsv.setId("#123");
report.addResult().setReference("#123");
```

Both of these changes make the test pass for me. Is there a use case for having contained resources be included even if they are not referred to?

**Comment by jamesagnew** [comment] 2015-04-03 19:48
I've just pushed a fix to #146 and I'm pushing a new 1.0-SNAPSHOT build to maven.
I'm hoping this will also resolve this issue. Can you confirm and close this bug if so?

**Comment by baopingle** [comment] 2015-04-13 07:45
Sorry for later response, I have to say it still has a problem even if add the result for contained resource. See my follow test case

Observation obsv = new Observation();
//set the id for the observation
obsv.setId(new IdDt(123456));
report.getContained().getContainedResources().add(obsv);
report.addResult().setResource(obsv);
IParser parser = new FhirContext().newXmlParser().setPrettyPrint(true);
    String message = parser.encodeResourceToString(report);
    System.out.println(message);
    Assert.assertTrue(StringUtils.contains(message, "contained")); //failed, no contained elements for it

**Comment by KevinMayfield** [comment] 2015-05-22 15:11
James,

Your suggestion to link via the references worked for me  

                patient = new Patient();
		patient.setId(new IdDt("#pat"));
		
		docRef.getSubject().setReference(new IdDt("#pat")); 
		
		Boolean result = docRef.getContained().getContainedResources().add(patient);


I had also tried the route baopingle had gone for first.

**Comment by jamesagnew** [comment] 2015-05-22 16:59
Yikes, just realized I hadn't followed up on this ticket. Thanks for mentioning that it worked, @KevinMayfield.

@baopingle : In your example, the resource doesn't get added as a contained resource because it has a non-local ID. If you change:
`obsv.setId(new IdDt(123456));`
to
`obsv.setId(new IdDt("#123456"));`
it should work.

**Comment by Gyannea** [comment] 2015-07-02 15:37
I have to admit the use of references to see the contained resource makes no sense to me. First of all, why would someone include a resource if it were not important? Seems like a lot of work for nothing. Furthermore, a BaseResource does not have a means to point to a referenced resource though there IS a method to add a contained resource.

For example if I want to represent the properties of an IEEE 11073 20601 device as a FHIR resource I need to populate the Device resource but also the DeviceComponent Resource as the production specification data is only present on the DeviceComponent. So I make the DeviceComponent a resource contained inside the Device resource and send it as part of a bundle. The recipient will parse the JSON/XML string and search all the fields inside the Device to obtain all the properties exposed.

**Comment by jamesagnew** [comment] 2015-07-03 19:01
Hi @Gyannea ,

Unfortunately this wouldn't actually be valid FHIR. You can only contain resources where there is a link to those resources from the container.

It might be worth taking the question of how to do this modelling over to the FHIR mailing list. I'm not a domain expert on this of course, but there are others who would probabyl have idea about how to accomplish what you're trying to accomplish.

**Closed** 2020-03-27 07:43 UTC
Labels: wontfix
