### ISSUE TITLE
Using UnauthorizedException results in incomplete http response in Tomcat

### ISSUE THREAD

**Issue by dnperfors** [jamesagnew/hapi-fhir#1767] opened 2020-03-20 09:24 UTC
**Describe the bug**
When throwing and AuthenticationException as described in the [documentation](https://hapifhir.io/hapi-fhir/docs/security/authorization_interceptor.html), the http response shows `HTTP/1.1 401 ` instead of `HTTP/1.1 401 Unauthorized`. For us this leads to issues during testing where we validate the 'Unauthorized' part.

Note that this only occurs when running inside Tomcat, using Jetty the response is correct.

**To Reproduce**

- Create an AuthorizationIntercepter as described in the [documentation](https://hapifhir.io/hapi-fhir/docs/security/authorization_interceptor.html)
- Make a request that will throw the AuthenticationException
- Capture the raw http response, it will look like:
```
HTTP/1.1 401
X-Powered-By: HAPI FHIR 4.2.0 REST Server (FHIR Server; FHIR 3.0.2/DSTU3)
Content-Type: text/plain;charset=UTF-8
Content-Length: 45
Date: Fri, 20 Mar 2020 09:21:00 GMT

Missing or invalid Authorization header value
```

**Expected behavior**
The following response is expected:
```
HTTP/1.1 401 Unauthorized
X-Powered-By: HAPI FHIR 4.2.0 REST Server (FHIR Server; FHIR 3.0.2/DSTU3)
Content-Type: text/plain;charset=UTF-8
Content-Length: 45
Date: Fri, 20 Mar 2020 09:21:00 GMT

Missing or invalid Authorization header value
```

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.2.1-SNAPSHOT
 - OS: docker container, using tomcat server from the hapi-fhir-starter project.

**Comment by tadgh** [comment] 2020-03-20 17:04
Heya, thanks for the report. 

I'm unable to replicate this on either 4.2.0 or master:
![](https://i.imgur.com/F7trkMr.png)

Can you point me to the actual artifact you're using, or provide a reproducible example?

**Comment by dnperfors** [comment] 2020-03-21 15:08
By the looks of it you tried it using jetty, the docker container runs the starter in tomcat, I updated the issue. When I run using jetty, I get the same result:

```
dnperfors@YY155960:~$ curl -v http://localhost:8080/hapi-fhir-jpaserver/fhir/Medication
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /hapi-fhir-jpaserver/fhir/Medication HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 401
< X-Powered-By: HAPI FHIR 4.2.0 REST Server (FHIR Server; FHIR 3.0.2/DSTU3)
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 45
< Date: Sat, 21 Mar 2020 15:01:15 GMT
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
Missing or invalid Authorization header value

dnperfors@YY155960:~$ curl -v http://localhost:8080/fhir/Medication
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /fhir/Medication HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Date: Sat, 21 Mar 2020 15:02:15 GMT
< X-Powered-By: HAPI FHIR 4.2.0 REST Server (FHIR Server; FHIR 3.0.2/DSTU3)
< Content-Type: text/plain;charset=utf-8
< Content-Length: 45
< Server: Jetty(9.4.24.v20191120)
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by tadgh** [comment] 2020-03-22 23:21
So I've managed to replicate this! But I've also found the same behaviour in all Tomcat servers, serving  anything that returns a 401(including the internal tomcat status manager). Here's me querying the status manager without authentication: 
![](https://i.gyazo.com/5900674de42718997b92cd470f496a0b.png)

Querying for endpoints that end in 200 or 302 result in the same text-less response. 
If you know of a fix to this, let me know, but it seems to be just how tomcat returns response codes, at least from what I can find. I would welcome more information on this if you have it, but for now it appears as though this may be out of our hands.

**Comment by tadgh** [comment] 2020-03-22 23:27
Actually, looks like there is a bugzilla for this in tomcat: https://bz.apache.org/bugzilla/show_bug.cgi?id=60362. Feel free to read through that, as they may have patched it or have a workaround provided within. Going to close this here as this is not in the purview of HAPI FHIR

**Comment by tadgh** [comment] 2020-03-22 23:31
Looks like there is a tomcat config option `sendReasonPhrase`. Grep through [here](https://tomcat.apache.org/tomcat-8.5-doc/config/http.html#Common_Attributes) to find it. This will apparently work for 8.5.x but is deprecated, and totally removed for tomcat9.

**Closed** 2020-03-22 23:32 UTC

**Comment by dnperfors** [comment] 2020-03-23 06:26
Thanks @tadgh for pointing to the Tomcat issue. I will take a further look there.
