### ISSUE TITLE
MedicationDispenseStatus missing in R4?

### ISSUE THREAD

**Issue by keithboone** [jamesagnew/hapi-fhir#1527] opened 2019-10-06 04:11 UTC
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**
org.hl7.fhir.r4.model.MedicationDispense.MedicationDispenseStatus missing in 4.0.0

**To Reproduce**

**Expected behavior**
I was expecting there to be a class for the CodeType associated with MedicationDispenseStatus in R4 MedicationDispense

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.0.0
 - OS: N/A
 - Browser N/A

**Additional context**
I was updating Version converters that I've patched and found this.  Eventually I'll get those to you as well.

**Comment by keithboone** [comment] 2019-10-06 05:37
I expect same for MedicationAdministrationStatus

**Comment by jamesagnew** [comment] 2019-10-06 16:46
This is actually a duplicate of this bug: https://github.com/jamesagnew/hapi-fhir/issues/1527

**Comment by jamesagnew** [comment] 2019-10-06 16:47
Oops, clearly a self link is not the right link :)

Duplicate of this bug: https://github.com/hapifhir/org.hl7.fhir.core/issues/70

**Closed by jamesagnew** 2019-10-06 16:46 UTC
