### ISSUE TITLE
NoClassDefFoundError for XmlUtil$ExtendedEntityReplacingXmlResolver on Android

### ISSUE THREAD

**Issue by FilipDomazet** [jamesagnew/hapi-fhir#450] opened 2016-09-16 13:27 UTC
When using XML encoding in HAPI version 2.0 on Android and error occurs when the server reply is being parsed. This was tested on API levels 23 and 24. The jar used is hapi-fhir-android with dstu2 classifier. The stack trace is included. 
[NoClassDefFound XmlUtil$ExtEntReplXmlResolver Android.txt](https://github.com/jamesagnew/hapi-fhir/files/476885/NoClassDefFound.XmlUtil.ExtEntReplXmlResolver.Android.txt)

We have checked the jar, and there is indeed a class file called XmlUtil$ExtendedEntityReplacingXmlResolver in the ca/uhn/fhir/util/ directory, so we are not sure why this error occurs.

**Comment by FilipDomazet** [comment] 2016-09-19 07:56
Forgot to mention that this issue does not occur in version 1.6.

**Comment by jamesagnew** [comment] 2016-09-29 16:02
I believe this is caused by the accidental removal of the Woodstox library from the Android builds. I'm going to check in a fix shortly and I'm pushing new `2.1-SNAPSHOT` builds now. Do you mind to verify if this fix corrects your issue?

**Comment by FilipDomazet** [comment] 2016-10-07 07:45
It seems to be working now.

**Comment by jamesagnew** [comment] 2016-10-07 12:25
Closing

**Closed by jamesagnew** 2016-10-07 12:25 UTC
