### ISSUE TITLE
download link for couchbase??

### ISSUE THREAD

**Issue by jayashreeb081767** [jamesagnew/hapi-fhir#490] opened 2016-11-09 11:19 UTC
unable to download the couchbase db

**Comment by jamesagnew** [comment] 2016-11-09 12:42
Please provide complete details about what you are trying to do, what steps
you took, what the problem is, etc.

Unfortunately this ticket does not have enough detail to be useful.

sent from my phone.

**Comment by jayashreeb081767** [comment] 2016-11-10 04:38
hi james,
i'm getting the below exception. so please provide the driverclass
Exception in thread "main" java.sql.SQLException: No suitable driver found for couchbase://127.0.0.1/8091
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at ca.uhn.fhir.jpa.demo.RetriveDataUsingCouchBase.main(RetriveDataUsingCouchBase.java:19)

**Comment by jamesagnew** [comment] 2016-11-10 11:57
There is no class in HAPI's codebase called RetriveDataUsingCouchBase.java

**Comment by jamesagnew** [comment] 2016-11-21 21:08
I'm closing this ticket, please see the comment here for details: https://github.com/jamesagnew/hapi-fhir/issues/498

If you want to open any more tickets please leave a complete description of what you are trying to accomplish as well as a DETAILED explanation of the steps you have taken, any steps you have taken, etc.

**Closed by jamesagnew** 2016-11-21 21:08 UTC
