### ISSUE TITLE
HAPI FHIR - Core Library  FAILURE

### ISSUE THREAD

**Issue by GitHubUNCStudent** [jamesagnew/hapi-fhir#1472] opened 2019-09-05 05:39 UTC
I am getting the same problems as Issue Failed to build HAPI FHIR  #1356 opened Jun 21, 2019 by ckamann. It doesn't look like this issue was resolved for this user.

Like ckamann,  I was able to bypass the error [ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata (downstream) on project hapi-fhir-base: Execution downstream of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata failed.: NullPointerException -> 

by adding -Dmaven.buildNumber.skip=true

After skipping the codehaus.mojo:buildnumber  issue, I got stuck in the same place as ckamann.

 My logs from using the -X switch show the same 3 test failures for [INFO] HAPI FHIR - Core Library ........................... FAILURE [01:29 min]
as ckamann.

These 3 errors are:

[ERROR] testGetVersion(ca.uhn.fhir.i18n.HapiLocalizerTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError:

Expected: a string matching the pattern '[0-9]+.*'
     but: was "(unknown)"
        at ca.uhn.fhir.i18n.HapiLocalizerTest.testGetVersion(HapiLocalizerTest.java:38)

[ERROR] testProperties(ca.uhn.fhir.util.VersionUtilTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError:

Expected: not (null or a blank string)
     but: was null
        at ca.uhn.fhir.util.VersionUtilTest.testProperties(VersionUtilTest.java:14)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.109 s <<< FAILURE! - in ca.uhn.fhir.util.VersionEnumTest
[ERROR] testCurrentVersionExists(ca.uhn.fhir.util.VersionEnumTest)  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError:

Expected: a collection containing "V(unknown)"
     but: mismatches were: [was "V2_5_0", was "V3_0_0", was "V3_1_0", was "V3_2_0", was "V3_3_0", was "V3_4_0", was "V3_5_0", was "V3_6_0", was "V3_7_0", was "V3_8_0", was "V4_0_0"]
        at ca.uhn.fhir.util.VersionEnumTest.testCurrentVersionExists(VersionEnumTest.java:24)

You advised ckamann that he needs to debug.

I don't even know where to start debugging:  

ca.uhn.fhir.util.VersionEnumTest
ca.uhn.fhir.util.VersionUtilTest
ca.uhn.fhir.i18n.HapiLocalizerTest

Can you please help?

Some other notes:

mvn -version

Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00)
Maven home: C:\Program Files\Apache_Maven\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by jamesagnew** [comment] 2019-09-05 09:46
Duplicate of #1356 - Please comment on that bug

**Closed by jamesagnew** 2019-09-05 09:46 UTC
